# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.Category'),
        ),
    ]
