# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coupon.Category'),
            preserve_default=False,
        ),
    ]
